module.exports = function(app) {
    var schema=[
        {
            name:'Hall',
            image:{
                on:'images/on.jpg',
                off:'images/off.jpg'
            },
            status:21,
            switch:0
        },
        {
            name:'Kitchen',
            image:{
                on:'images/on.jpg',
                off:'images/off.jpg'
            },
            status:22,
            switch:2
        },
        {
            name:'Kitchen Cabinets',
            image:{
                on:'images/on.jpg',
                off:'images/off.jpg'
            },
            status:23,
            switch:3
        },
        {
            name:'Lounge',
            image:{
                on:'images/on.jpg',
                off:'images/off.jpg'
            },
            status:24,
            switch:7
        },
        {
            name:'Lounge wall',
            image:{
                on:'images/on.jpg',
                off:'images/off.jpg'
            },
            status:25,
            switch:1
        },
        {
            name:'Bedroom',
            image:{
                on:'images/on.jpg',
                off:'images/off.jpg'
            },
            status:27,
            switch:4
        },
        {
            name:'Boudoir',
            image:{
                on:'images/on.jpg',
                off:'images/off.jpg'
            },
            status:28,
            switch:5
        },
        {
            name:'Patio',
            image:{
                on:'images/on.jpg',
                off:'images/off.jpg'
            },
            status:29,
            switch:6
        }
    ];
    var light=require('./lights')(app);
    return {
        sockets:require('./sockets')(app),
        lights:schema.map(l => new light(app,l))
    };
}