module.exports = function(app) {
    var schema=[
        {
            name:'Hall',
            image:{
                on:'images/on.jpg',
                off:'images/off.jpg'
            },
            status:26,
            switch:2
        },
        {
            name:'Kitchen',
            image:{
                on:'images/on.jpg',
                off:'images/off.jpg'
            },
            status:22,
            switch:3
        },
        {
            name:'Kitchen Cabinets',
            image:{
                on:'images/on.jpg',
                off:'images/off.jpg'
            },
            status:23,
            switch:4
        },
        {
            name:'Lounge',
            image:{
                on:'images/on.jpg',
                off:'images/off.jpg'
            },
            status:24,
            switch:17
        },
        {
            name:'Lounge wall',
            image:{
                on:'images/on.jpg',
                off:'images/off.jpg'
            },
            status:25,
            switch:27
        },
        {
            name:'Bedroom',
            image:{
                on:'images/on.jpg',
                off:'images/off.jpg'
            },
            status:27,
            switch:22
        },
        {
            name:'Boudoir',
            image:{
                on:'images/on.jpg',
                off:'images/off.jpg'
            },
            status:28,
            switch:14
        },
        {
            name:'Patio',
            image:{
                on:'images/on.jpg',
                off:'images/off.jpg'
            },
            status:29,
            switch:15
        }
    ];
    var light=require('./lights')(app);
    return {
        lights:schema.map(l => new light(app,l)),
        sockets:require('./sockets')(app)
    };
}